baseURL = "https://willbaxter.info/"
languageCode = "en-us"
title = "Will Baxter"
theme = "anatole"

[params]
author = "Will Baxter"
description = "Professional and personal development website."

[[params.socialIcons]]
  icon = "fa-brands fa-github"
  title = "GitHub"
  url = "https://github.com/willbaxter"

[[params.socialIcons]]
  icon = "fa-brands fa-twitter"
  title = "Twitter"
  url = "https://twitter.com/willbaxter"
