name: Build & Deploy Hugo site

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true      # Fetch themes
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Install Embedded Dart Sass
        run: |
          EMBEDDED_VER="1.77.4"
          curl -sL https://github.com/sass/dart-sass/releases/download/${EMBEDDED_VER}/sass_embedded-${EMBEDDED_VER}-linux-x64.tar.gz | tar -xz
          echo "$PWD/sass_embedded" >> $GITHUB_PATH
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages 