name: Build & Deploy Hugo site

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      DART_SASS_EMBEDDED_VERSION: "1.77.5"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true      # Fetch themes
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
      - name: Install Dart Sass Embedded
        run: |
          curl -LJO https://github.com/sass/dart-sass-embedded/releases/download/${{ env.DART_SASS_EMBEDDED_VERSION }}/sass_embedded-${{ env.DART_SASS_EMBEDDED_VERSION }}-linux-x64.tar.gz
          tar -xzf sass_embedded-${{ env.DART_SASS_EMBEDDED_VERSION }}-linux-x64.tar.gz
          echo "$PWD/sass_embedded" >> $GITHUB_PATH
      - name: Build
        run: hugo --minify
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages 